### ISSUE TITLE
Some links on combine.org to specifications broken due to new site

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-org-website#31]
Just noticed that some links are not working on co.mbine.org.
E.g. on http://co.mbine.org/specifications/sbml.level-3.version-2.core.release-2

http://sbml.org/Special/specifications/sbml-level-3/version-2/core/release-2/sbml-level-3-version-2-release-2-core.pdf

I.e. the links for the specifications on co.mbine.org should be checked/updated or the documents should be provided under the correct urls in the new page.

**Comment by mhucka** [comment]
I've been investigating how to do this, and good news: it turns out it's pretty easy to create aliases in Hugo. What is required is to put an `aliases` variable in the index file of a page, and as the value of the variable, list URLs that are the old/other URLs that should be redirected to this index page. So, for example, in the `_index.md` file at `/software/`, I added this line in the TOML block at the top:

```
aliases = ["/Software"]
```

Multiple aliases can be defined (per [the Hugo docs](https://gohugo.io/content-management/urls/#toml-front-matter)).

We still need to find all the URLs that need to be aliased …

**Comment by mhucka** [comment]
Turns out that it required a more complicated approach to get the co.mbine.org links to work. It took a while, but I believe I have linked all the specs from co.mbine.org.

The `/Special` in the file names only appeared in some co.mbine.org entries and were actually a mistake (an artifact of the structure of the old sbml.org).  I updated the co.mbine.org pages to omit that part from the destination URLs.

If you find any that are still wrong, please reopen this ticket and note them here.

**Comment by matthiaskoenig** [comment]
Perfect. Thanks for fixing this.
